//
// Created by magali on 01/05/19.
//

#ifndef TALLER_MARVEL_CAPCOM_EVENTTOVALUEMAPPER_CHARSELECT_2_H
#define TALLER_MARVEL_CAPCOM_EVENTTOVALUEMAPPER_CHARSELECT_2_H


class EventToValueMapper_charSelect_2 {

};


#endif //TALLER_MARVEL_CAPCOM_EVENTTOVALUEMAPPER_CHARSELECT_2_H
