//
// Created by arielpm on 16/05/19.
//

#ifndef TALLER_MARVEL_CAPCOM_GAMEOBJECT_SERVER_H
#define TALLER_MARVEL_CAPCOM_GAMEOBJECT_SERVER_H


class GameObject_server {

};


#endif //TALLER_MARVEL_CAPCOM_GAMEOBJECT_SERVER_H
