//
// Created by trocchi on 6/8/19.
//

#ifndef TALLER_MARVEL_CAPCOM_CAPTAINAMERICAAUDIOMANAGER_H
#define TALLER_MARVEL_CAPCOM_CAPTAINAMERICAAUDIOMANAGER_H


class CaptainAmericaAudioManager {

};


#endif //TALLER_MARVEL_CAPCOM_CAPTAINAMERICAAUDIOMANAGER_H
